name: Laravel

on:
  push:
    branches: [ "develop" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        run: docker compose build
      
      - name: exec docker container bash
        run: make bash
      
      - name: exec date
        run: date
